SSID = 'TEST_BEACON';
beaconInterval = 1;
bitsPerByte = 8;
frameBodyConfig = wlanMACManagementConfig;
frameBodyConfig.BeaconInterval = beaconInterval;
frameBodyConfig.SSID = SSID;
dsElementID = 3;
chNum = 140;
dsInformation = dec2hex(chNum, 2);
frameBodyConfig = frameBodyConfig.addIE(dsElementID, dsInformation);
beaconFrameConfig = wlanMACFrameConfig('FrameType', 'Beacon');
beaconFrameConfig.ManagementConfig = frameBodyConfig;
[beacon, mpduLength] = wlanMACFrame(beaconFrameConfig, 'OutputFormat', 'bits');
cfgNonHT = wlanNonHTConfig;
cfgNonHT.PSDULength = mpduLength; 
waveform = wlanWaveformGenerator(beacon, cfgNonHT, 'IdleTime', beaconInterval*1024e-6);
Fs = wlanSampleRate(cfgNonHT); 
plot(real(waveform));
length(waveform);