% Generated by MATLAB(R) 9.7 (R2019b) and WLAN Toolbox 2.2 (R2019b).
% Generated on: 14-Mar-2020 09:25:50

%% Generate 802.11a/g/j (OFDM) Waveform
% 802.11a/g/j (OFDM) configuration:
nonHTCfg = wlanNonHTConfig('Modulation', 'OFDM', ...
    'ChannelBandwidth', 'CBW20', ...
    'MCS', 0, ...
    'PSDULength', 1000);

numPackets = 1;
% input bit source:
in = randi([0, 1], 1000, 1);


% waveform generation:
waveform = wlanWaveformGenerator(in, nonHTCfg, ...
    'NumPackets', numPackets, ...
    'IdleTime', 0, ...
    'ScramblerInitialization', 93, ...
    'WindowTransitionTime', 1e-07);

Fs = wlanSampleRate(nonHTCfg); 								 % sample rate of waveform

%% Visualize 802.11a/g/j (OFDM) Waveform
% Spectrum Analyzer
spectrum = dsp.SpectrumAnalyzer('SampleRate', Fs);
spectrum(waveform);
release(spectrum);


