function plot_labels(xlab,ylab)
set(gca,'fontsize',15,'FontName','MyriadPro-Regular');
set(gca, ...
    'Box' , 'off' , ...
    'TickDir' , 'out' , ...
    'TickLength' , [.02 .02] , ...
    'XMinorTick' , 'off' , ...
    'YMinorTick' , 'off' , ...
    'YGrid' , 'off' , ...
    'XGrid', 'off',...
    'LineWidth' , 1 );
grid off;
[ax,l1]=suplabel(xlab); 
[ax,l2]=suplabel(ylab,'y'); 
set(l1,'FontName' , 'MyriadPro-Regular','FontSize',15); %Font size of labels
set(l2,'FontName' , 'MyriadPro-Regular','FontSize',15); %Font size of labels
 
end