function p1=plot_preliminaries(x,y,color_index,varargin)

colors={'salmon','skyblue','palegreen','gold','grey','orange','violet','salmon','skyblue','salmon','skyblue','palegreen','gold','grey','orange','violet','salmon','skyblue','salmon','skyblue','palegreen','gold','grey','orange','violet','salmon','skyblue','salmon','skyblue','palegreen','gold','grey','orange','violet','salmon','skyblue','salmon','skyblue','palegreen','gold','grey','orange','violet','salmon','skyblue','salmon','skyblue','palegreen','gold','grey','orange','violet','salmon','skyblue','salmon','skyblue','palegreen','gold','grey','orange','violet','salmon','skyblue','salmon','skyblue','palegreen','gold','grey','orange','violet','salmon','skyblue','salmon','skyblue','palegreen','gold','grey','orange','violet','salmon','skyblue','salmon','skyblue','palegreen','gold','grey','orange','violet','salmon','skyblue','salmon','skyblue','palegreen','gold','grey','orange','violet','salmon','skyblue','salmon','skyblue','palegreen','gold','grey','orange','violet','salmon','skyblue','salmon','skyblue','palegreen','gold','grey','orange','violet','salmon','skyblue','salmon','skyblue','palegreen','gold','grey','orange','violet','salmon','skyblue'};
colors2={'darkred','blue','darkgreen','goldenrod','black','orangered','magenta','darkred','blue','darkred','blue','darkgreen','goldenrod','black','orangered','magenta','darkred','blue','darkred','blue','darkgreen','goldenrod','black','orangered','magenta','darkred','blue','darkred','blue','darkgreen','goldenrod','black','orangered','magenta','darkred','blue','darkred','blue','darkgreen','goldenrod','black','orangered','magenta','darkred','blue','darkred','blue','darkgreen','goldenrod','black','orangered','magenta','darkred','blue','darkred','blue','darkgreen','goldenrod','black','orangered','magenta','darkred','blue','darkgreen','goldenrod','black','orangered','magenta','darkred','blue','darkgreen','goldenrod','black','orangered','magenta','darkred','blue','darkred','blue','darkgreen','goldenrod','black','orangered','magenta','darkred','blue','darkred','blue','darkgreen','goldenrod','black','orangered','magenta','darkred','blue','darkred','blue','darkgreen','goldenrod','black','orangered','magenta','darkred','blue','darkred','blue','darkgreen','goldenrod','black','orangered','magenta','darkred','blue','darkred','blue','darkgreen','goldenrod','black','orangered','magenta','darkred','blue','darkred','blue','darkgreen','goldenrod','black','orangered','magenta','darkred','blue','darkgreen','goldenrod','black','orangered','magenta'};

if nargin>3
if strcmp(varargin{1},'nomarker')
p1=plot(x,y,'Marker', 'none', ...
    'Color',rgb(colors2{color_index}), ...
    'Linewidth',1.75, ...
    'MarkerSize' ,11 , ...
'MarkerEdgeColor' , 'none' , ...
    'MarkerFaceColor' , rgb(colors{color_index})); hold on;
 grid on;
elseif strcmp(varargin{1},'noline')
    p1=plot(x,y,'Marker', 'o', ...
    'Color',rgb(colors2{color_index}), ...
    'Linestyle','none',...
    'Linewidth',1.5, ...
    'MarkerSize' ,11 , ...
 'MarkerEdgeColor' , 'none' , ...
    'MarkerFaceColor' , rgb(colors{color_index})); hold on;
 grid on;
end
else
    p1=plot(x,y,'Marker', 'o', ...
    'Color',rgb(colors2{color_index}), ...
    'Linewidth',1, ...
    'MarkerSize' ,9 , ...
'MarkerEdgeColor' , 'none' , ...
    'MarkerFaceColor' , rgb(colors{color_index})); hold on;
 grid on;
end

set(gca,'fontsize',15,'FontName','MyriadPro-Regular');
set(gca, ...
    'Box' , 'off' , ...
    'TickDir' , 'in' , ...
    'TickLength' , [.02 .02] , ...
    'XMinorTick' , 'on' , ...
    'YMinorTick' , 'on' , ...
    'YGrid' , 'on' , ...
    'XGrid', 'on',...
    'LineWidth' , 1 );
grid on;
end